/**
 * GitHub Copilot Cloud Agent Support
 *
 * Generates copilot-setup-steps.yml and .github/agents/openspec.agent.md
 * when the github-copilot tool is selected during init/update.
 * These files enable the GitHub Copilot coding agent (cloud) to use the
 * OpenSpec CLI in its ephemeral dev environment.
 */

import path from 'path';
import { promises as fs } from 'fs';
import { FileSystemUtils } from '../../utils/file-system.js';

const COPILOT_TOOL_ID = 'github-copilot';
const OPENSPEC_MANAGED_MARKER = 'Generated by OpenSpec for GitHub Copilot coding agent support.';

/**
 * Check if a tool list includes github-copilot.
 */
export function includesGitHubCopilot(toolIds: string[]): boolean {
  return toolIds.includes(COPILOT_TOOL_ID);
}

/**
 * Generate the copilot-setup-steps.yml workflow file content.
 * This workflow pre-installs the OpenSpec CLI in the Copilot coding agent's
 * ephemeral GitHub Actions environment.
 */
export function generateCopilotSetupSteps(): string {
  return `# ${OPENSPEC_MANAGED_MARKER}

${generateCopilotSetupStepsBody()}`;
}

function generateCopilotSetupStepsBody(): string {
  return `name: "Copilot Setup Steps"

# Runs automatically when changed (for validation) and can be triggered manually.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called \`copilot-setup-steps\` for Copilot coding agent to pick it up.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSpec CLI
        run: npm install -g @fission-ai/openspec

      - name: Verify OpenSpec CLI
        run: openspec --version
`;
}

/**
 * Generate the .github/agents/openspec.agent.md custom agent file content.
 * This tells the GitHub Copilot coding agent how to use the OpenSpec CLI.
 */
export function generateCopilotAgentFile(): string {
  return generateCopilotAgentFileBody(true);
}

function generateCopilotAgentFileBody(includeManagedMarker = false): string {
  const managedMarker = includeManagedMarker
    ? `<!-- ${OPENSPEC_MANAGED_MARKER} -->\n\n`
    : '';

  return `---
name: OpenSpec
description: "Manages OpenSpec changes, specs, and workflows using the OpenSpec CLI. Use this agent for proposing changes, exploring ideas, validating artifacts, checking status, and archiving completed work."
tools:
  - "execute"
  - "read"
  - "search"
  - "edit"
---

${managedMarker}# OpenSpec Agent

You are a specialized agent for managing OpenSpec workflows. Before using the \`openspec\` CLI, run \`openspec --version\`. If it is unavailable, install it with \`npm install -g @fission-ai/openspec\`.

## What is OpenSpec?

OpenSpec is a structured change management system for codebases. It organizes work into **changes** with planning artifacts (proposals, specs, designs, tasks) that guide implementation.

## Available Commands

### Agent-Compatible CLI Commands (prefer \`--json\` for structured output)

| Command | Purpose |
|---------|---------|
| \`openspec list [--json]\` | List all changes and specs |
| \`openspec show <item> [--json]\` | View a specific change or spec |
| \`openspec validate [--all] [--json]\` | Validate changes and specs for issues |
| \`openspec status [--change <name>] [--json]\` | Show artifact progress for a change |
| \`openspec instructions [artifact] [--change <name>] [--json]\` | Get next-step instructions for a change |
| \`openspec templates [--json]\` | List available templates |
| \`openspec schemas [--json]\` | List available workflow schemas |
| \`openspec archive <change> --json [--yes]\` | Archive a completed change; use \`--yes\` only after confirming all tasks are complete |

### Interactive CLI Commands (use when prompted by the user)

| Command | Purpose |
|---------|---------|
| \`openspec init\` | Initialize OpenSpec in the project |
| \`openspec update\` | Update OpenSpec configuration and artifacts |
| \`openspec view\` | Interactive dashboard |
| \`openspec config\` | View or modify settings |

## Workflow

When asked to work with OpenSpec, follow this pattern:

1. **Find the change**: Run \`openspec list --json\` to see active changes.
2. **Check progress**: Run \`openspec status --change <name> --json\` for the selected change.
3. **Follow instructions**: Run \`openspec instructions [artifact] --change <name> --json\` for the next artifact.
4. **Validate before completing**: Run \`openspec validate <name> --json\`.

## Creating New Changes

When the user wants to propose a new change:

1. Run \`openspec new change <name>\`.
2. Run \`openspec status --change <name> --json\` to see the artifact sequence.
3. Use \`openspec instructions [artifact] --change <name> --json\` before creating each artifact.
4. Run \`openspec validate <name> --json\` when the artifacts are complete.

## Key Directories

- \`openspec/\` — Root OpenSpec directory
- \`openspec/changes/\` — Active changes with their artifacts
- \`openspec/config.yaml\` — Project configuration

## Best Practices

- Always use \`--json\` flag when you need to parse output programmatically
- Run \`openspec validate\` after creating or modifying artifacts
- Check \`openspec status\` before starting work to understand the current state
- When archiving, ensure all tasks are completed and validated first
`;
}

function generatePreviousCopilotAgentFileBody(includeManagedMarker = false): string {
  let content = generateCopilotAgentFileBody();
  content = replaceRequired(
    content,
    'You are a specialized agent for managing OpenSpec workflows. Before using the `openspec` CLI, run `openspec --version`. If it is unavailable, install it with `npm install -g @fission-ai/openspec`.',
    'You are a specialized agent for managing OpenSpec workflows. You have access to the `openspec` CLI through shell commands, pre-installed in the development environment via `copilot-setup-steps.yml`.',
    'previous CLI access sentence'
  );
  content = replaceRequired(
    content,
    '| `openspec archive <change> --json [--yes]` | Archive a completed change; use `--yes` only after confirming all tasks are complete |',
    '| `openspec archive <change>` | Archive a completed change |',
    'previous archive command row'
  );

  if (!includeManagedMarker) {
    return content;
  }

  return replaceRequired(
    content,
    '\n# OpenSpec Agent',
    `\n<!-- ${OPENSPEC_MANAGED_MARKER} -->\n\n# OpenSpec Agent`,
    'previous agent heading'
  );
}

function generateLegacyCopilotAgentFileBody(): string {
  let content = generatePreviousCopilotAgentFileBody();
  content = replaceRequired(
    content,
    `## Workflow

When asked to work with OpenSpec, follow this pattern:

1. **Find the change**: Run \`openspec list --json\` to see active changes.
2. **Check progress**: Run \`openspec status --change <name> --json\` for the selected change.
3. **Follow instructions**: Run \`openspec instructions [artifact] --change <name> --json\` for the next artifact.
4. **Validate before completing**: Run \`openspec validate <name> --json\`.

## Creating New Changes

When the user wants to propose a new change:

1. Run \`openspec new change <name>\`.
2. Run \`openspec status --change <name> --json\` to see the artifact sequence.
3. Use \`openspec instructions [artifact] --change <name> --json\` before creating each artifact.
4. Run \`openspec validate <name> --json\` when the artifacts are complete.`,
    `## Workflow

When asked to work with OpenSpec, follow this pattern:

1. **Check current state**: Run \`openspec status --json\` to understand what changes exist and their progress.
2. **Follow instructions**: Run \`openspec instructions --json\` to get context-aware next steps.
3. **Validate before completing**: Run \`openspec validate --all --json\` to ensure artifacts are correct.

## Creating New Changes

When the user wants to propose a new change:

1. Create the change directory under \`openspec/changes/<change-name>/\`
2. Generate the required planning artifacts based on the project's configured workflow schema
3. Run \`openspec validate --json\` to verify the artifacts are well-formed`,
    'legacy workflow guidance'
  );
  content = replaceRequired(
    content,
    `tools:
  - "execute"
  - "read"
  - "search"
  - "edit"`,
    `tools:
  - "terminal"`,
    'legacy tool alias'
  );
  content = replaceRequired(
    content,
    'You are a specialized agent for managing OpenSpec workflows. You have access to the `openspec` CLI through shell commands, pre-installed in the development environment via `copilot-setup-steps.yml`.',
    'You are a specialized agent for managing OpenSpec workflows. You have access to the `openspec` CLI which is pre-installed in the development environment via `copilot-setup-steps.yml`.',
    'legacy CLI access sentence'
  );
  content = replaceRequired(
    content,
    '| `openspec status [--change <name>] [--json]` | Show artifact progress for a change |',
    '| `openspec status [--json]` | Show artifact progress for active changes |',
    'legacy status command row'
  );
  content = replaceRequired(
    content,
    '| `openspec instructions [artifact] [--change <name>] [--json]` | Get next-step instructions for a change |',
    '| `openspec instructions [--json]` | Get next-step instructions for a change |',
    'legacy instructions command row'
  );
  return replaceRequired(
    content,
    '- `openspec/config.yaml` — Project configuration',
    `- \`openspec/config.yaml\` — Project configuration
- \`openspec/explorations/\` — Exploration documents`,
    'legacy exploration directory'
  );
}

function replaceRequired(
  content: string,
  searchValue: string,
  replaceValue: string,
  label: string
): string {
  if (!content.includes(searchValue)) {
    throw new Error(`Cannot build Copilot cloud file content: missing ${label}`);
  }
  return content.replace(searchValue, replaceValue);
}

/**
 * File paths (relative to project root) for the generated files.
 */
export const COPILOT_CLOUD_FILES = {
  setupSteps: path.join('.github', 'workflows', 'copilot-setup-steps.yml'),
  agent: path.join('.github', 'agents', 'openspec.agent.md'),
} as const;

const COPILOT_AGENT_ALTERNATE_FILE = path.join('.github', 'agents', 'openspec.md');

type CopilotCloudFile = (typeof COPILOT_CLOUD_FILES)[keyof typeof COPILOT_CLOUD_FILES];

const COPILOT_CLOUD_FILE_CONTENTS: Record<CopilotCloudFile, string> = {
  [COPILOT_CLOUD_FILES.setupSteps]: generateCopilotSetupSteps(),
  [COPILOT_CLOUD_FILES.agent]: generateCopilotAgentFile(),
};

function getLegacyCopilotCloudFileContents(relPath: CopilotCloudFile): string[] {
  if (relPath === COPILOT_CLOUD_FILES.setupSteps) {
    return [generateCopilotSetupStepsBody()];
  }

  return [
    generateCopilotAgentFileBody(),
    generatePreviousCopilotAgentFileBody(),
    generatePreviousCopilotAgentFileBody(true),
    generateLegacyCopilotAgentFileBody(),
  ];
}

function normalizeLineEndings(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

function isCurrentCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return normalizeLineEndings(content) === COPILOT_CLOUD_FILE_CONTENTS[relPath];
}

function isLegacyCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return getLegacyCopilotCloudFileContents(relPath).includes(normalizeLineEndings(content));
}

function isManagedCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return isCurrentCopilotCloudFile(relPath, content) || isLegacyCopilotCloudFile(relPath, content);
}

async function reconcileCopilotCloudFile(
  fullPath: string,
  relPath: CopilotCloudFile
): Promise<boolean> {
  const currentContent = COPILOT_CLOUD_FILE_CONTENTS[relPath];

  if (!(await FileSystemUtils.fileExists(fullPath))) {
    await FileSystemUtils.writeFile(fullPath, currentContent);
    return true;
  }

  const existingContent = await FileSystemUtils.readFile(fullPath);
  if (isCurrentCopilotCloudFile(relPath, existingContent)) {
    return false;
  }
  if (!isLegacyCopilotCloudFile(relPath, existingContent)) {
    return false;
  }

  await FileSystemUtils.writeFile(fullPath, currentContent);
  return true;
}

async function assertCreatableFilePath(filePath: string): Promise<void> {
  let candidate = path.dirname(filePath);

  while (true) {
    try {
      const stats = await fs.stat(candidate);
      if (!stats.isDirectory()) {
        throw new Error(`Parent path is not a directory: ${candidate}`);
      }
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }

    const parent = path.dirname(candidate);
    if (parent === candidate) {
      throw new Error(`Cannot resolve a directory ancestor for: ${filePath}`);
    }
    candidate = parent;
  }
}

async function assertMissingOrRegularFile(filePath: string): Promise<void> {
  try {
    const stats = await fs.stat(filePath);
    if (!stats.isFile()) {
      throw new Error(`Managed Copilot path is not a regular file: ${filePath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

async function classifyCopilotAgentReconciliation(
  agentPath: string,
  alternateAgentPath: string
): Promise<'reconcile' | 'skip' | 'remove-managed'> {
  if (!(await FileSystemUtils.fileExists(alternateAgentPath))) {
    return 'reconcile';
  }
  if (!(await FileSystemUtils.fileExists(agentPath))) {
    return 'skip';
  }

  const existingContent = await FileSystemUtils.readFile(agentPath);
  if (isManagedCopilotCloudFile(COPILOT_CLOUD_FILES.agent, existingContent)) {
    return 'remove-managed';
  }

  throw new Error(
    `Conflicting Copilot agent profiles: preserve either ${COPILOT_AGENT_ALTERNATE_FILE} or ${COPILOT_CLOUD_FILES.agent}`
  );
}

/**
 * Reconcile Copilot cloud agent files in the project directory.
 * Creates missing files and refreshes recognized legacy generated files while
 * preserving current generated content and user customizations.
 *
 * @returns Object indicating which files were written.
 */
export async function writeCopilotCloudFiles(
  projectPath: string
): Promise<{ setupStepsWritten: boolean; agentWritten: boolean }> {
  const setupStepsPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_CLOUD_FILES.setupSteps
  );
  const agentPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_CLOUD_FILES.agent
  );
  const alternateAgentPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_AGENT_ALTERNATE_FILE
  );

  await assertCreatableFilePath(setupStepsPath);
  await assertCreatableFilePath(agentPath);
  await assertMissingOrRegularFile(setupStepsPath);
  await assertMissingOrRegularFile(agentPath);
  await assertMissingOrRegularFile(alternateAgentPath);
  const agentReconciliation = await classifyCopilotAgentReconciliation(
    agentPath,
    alternateAgentPath
  );

  const setupStepsWritten = await reconcileCopilotCloudFile(
    setupStepsPath,
    COPILOT_CLOUD_FILES.setupSteps
  );
  let agentWritten = false;
  if (agentReconciliation === 'reconcile') {
    agentWritten = await reconcileCopilotCloudFile(agentPath, COPILOT_CLOUD_FILES.agent);
  } else if (agentReconciliation === 'remove-managed') {
    await fs.unlink(agentPath);
  }

  return { setupStepsWritten, agentWritten };
}

/**
 * Remove copilot cloud agent files from the project directory.
 * Used when github-copilot is deselected.
 *
 * @returns Number of files removed.
 */
export async function removeCopilotCloudFiles(projectPath: string): Promise<number> {
  let removed = 0;
  const managedPaths = Object.values(COPILOT_CLOUD_FILES).map((relPath) => ({
    relPath,
    fullPath: FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath),
  }));
  for (const { fullPath } of managedPaths) {
    await assertMissingOrRegularFile(fullPath);
  }

  for (const { relPath, fullPath } of managedPaths) {
    if (await FileSystemUtils.fileExists(fullPath)) {
      const content = await FileSystemUtils.readFile(fullPath);
      if (!isManagedCopilotCloudFile(relPath, content)) {
        continue;
      }

      await fs.unlink(fullPath);
      removed++;
    }
  }

  return removed;
}
